### PR TITLE
Add missing data cleanup features

### PR DESCRIPTION
**Pull request by kavj**
This adds some cleanup features and tools for handling missing data. It does not add in corresponding mpx implementations yet.

### CODE REVIEW

**Comment by tylerwmarrs** [comment]
I think this is mostly what we discussed. It looks like a couple of re-usable functions that any future algorithms may use for "skipping" invalid windows. Do you plan to adjust mpx to use this logic? That is an important piece of this that is missing.

**Comment by kavj** [comment]
These are intentionally reusable functions. They aren't optimized in any sense, but they're reasonable for preprocessing purposes.

I started on mpx, but it requires too much work if you want something out reasonably soon. I would prefer to put that off, but the easily reusable components are here.

**Comment by tylerwmarrs** [comment]
@vanbenschoten what do you think about pushing off the mpx additions? We still have Kevin waiting on this adjustment to be in plave.

Kaveh, do you want me to add the logic in? For the current implementation, it seems fairly simple. Correct me if my initial judgment is wrong on the effort.

**Comment by vanbenschoten** [comment]
I think holding off on MPX makes sense, provided we can push out streaming
more quickly (which IIRC wasn't necessarily dependent on MPX).

**Comment by tylerwmarrs** [comment]
I think everything looks good. I don't want to extend the scope of this work. We can discuss the original ask for mpx missing data issues in the open issue.

**Pull request merged**
